site_name: The Serene Digital Garden
theme:
  name: material
  custom_dir: theme
  language: ar
  direction: rtl
  logo: assets/logo-light.png
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Tajawal
    code: Tajawal

plugins:
  - search
  - blog:
      blog_dir: .
      blog_toc: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abokamal09
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ahmedkamaldev
      name: LinkedIn
