# General information
site_name: AK Blog
site_author: Ahmed Kamal
site_description: Linux and Open Source Software, and more content.
copyright: حقوق النشر &copy; 2024 - 2025 أحمد كمال
site_url: https://abokamal09.github.io
repo_url: https://github.com/abokamal09/abokamal09.github.io

# Themes settings
theme:
  language: ar
  custom_dir: overrides
  name: material
  logo: /assets/logo.png
  favicon: /assets/logo.png

  font:
    text: Tajawal

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/auto-fix
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: green
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: green
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    
    - content.code.copy

# CSS Style
extra_css:
  - assets/style/.css


# Plugins 
plugins:
  - offline
  - search
  - tags:
      tags_file: tags.md
  - glightbox

# MD Extentions
markdown_extensions:

  # Python Markdown
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - admonition
  - footnotes
  - tables
  - toc:
      title: On this page
      permalink: ⚓︎
      baselevel: 3
      toc_depth: 6
      separator: "_"
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic:
      mode: view

  # blog
  - meta

# Nav bar pages
nav:
  - الصفحة الرئيسية: index.md
  - المدونة: 
      # All blog content
      - posts.md
      - Posts/iot.md
  - عن المدونة: about.md
  - الأوسمة: tags.md

# Social links and Blog info
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/abokamal09
      name: Facebook
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ahmedkamaldev/
      name: Linkedin
      
  blog:
    dir: Posts
    author: Ahmed Kamal
    author_image: /assets/logo.png
    words_read_per_minute: 300
    list_length: 5
    extended_preview: true
